spring.application.name=nexcircle
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-frosty-shadow-a4vpb0ep-pooler.us-east-1.aws.neon.tech:5432/nexcircledb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zKNxQP7VGl4L
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#logging.level.root=DEBUG